### ISSUE TITLE
agent.py - KeyError @ line 68

### ISSUE THREAD

**Issue by kgagnon** [Javieracost/Flarelyzer#1]
Hi there, I just want to mention that I do not talk python, at all. I did a quick research and KeyError is when a dictionnary object is accessed but the key do not exists. I have no idea what that means. I will read more on this this week-end, just thought I'd let you know.

By the way, I wanted to learn python for a while, I will throw a few commits in this project for sure. Thanks !

➜  Flarelyzer git:(master) python Flarelyzer.py  
pluralMap loaded
Creating temporary socket file...
waiting for client...
Initializing memscan...
connected to notification server!
connected!
Client PID: 32338
===Memory analyzer started===
Notification agent error <type 'exceptions.KeyError'> - at line: 68
stopping memory scan upon request
--Memory scanner closed--
--Notification agent closed--

**Comment by Javieracost** [comment]
Hey. Yeah this happens when an unexpected plural item name is read. My bad, will fix in a moment!

**Comment by Kuwshi** [comment]
Thank you ! Do you know where we can chat on this repo ? I never found the place on github to talk without being on an issue thread. Anyways, all this to day, I have a lot of work already done on key remapping. I can probably bring this in.

**Comment by Javieracost** [comment]
Hmm not on this repo, but feel free to email me, you can find my address in my profile page!

**Comment by Javieracost** [comment]
Please test and let me know if i should close this issue.

**Comment by Javieracost** [comment]
Fixed with https://github.com/Javieracost/Flarelyzer/commit/98b87ee83700bb7b128240057bd2ebc5bfc463ca

**Comment by kgagnon** [comment]
Confirming the fix. Thank you !
