### ISSUE TITLE
Tibia client 11

### ISSUE THREAD

**Issue by Isark2** [Javieracost/Flarelyzer#4]
I'm really glad that you have made a Linux compatible version, but for me it doesn't find the Tibia client.

I'm assuming that it is becuase of version 11. Is there any quickfix, or fix at all coming? If it's supposed to be working for client 11, any other idea why it won't find the Tibia client?

// Isark

**Comment by Javieracost** [comment]
Hmm.. No, it wasnt developed with Tibia 11 in mind and i fear it probably wont support it for the time being (Goes without saying that all pull requests are welcome of course). On the other hand the 10.X client versions  should still work, so let me know if they dont because that'd be a bug!
Cheers

**Comment by Isark2** [comment]
Okay, thanks for the answer!

I'm really new to github so I don't know what a pull request would do, nor most other features. I'll read on a bit ;) 

I guess I'll have to move on without any tibia/flarelyzer for now since I don't really feel like downgrading client ^^

**Comment by Isark2** [comment]
Just got to know a bit more on how github works, sorry but I'm not familiar with Python. If I ever get some experience with Python, I could give pulling a chance to help you out.
